name: Push the Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dockerhubscretdeployment
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Build docker images
      run: docker build . --file Dockerfile --tag minsuzu/flaskappip

    - name: Push into Docker Hub
      run: docker push minsuzu/flaskappip



